### ISSUE TITLE
One issue when launching python tweepy; Keeps saying one of two messages 

### ISSUE THREAD

**Issue by g003223** [BotOrNot42/FOMORADIO#1]
python run.py
Loaded Configuration : /root/FOMORADIO/config/show_config.json
Loaded Configuration : /root/FOMORADIO/config/memory_config.json
Loaded Configuration : /root/FOMORADIO/config/fomo_config.json
Loaded Configuration : /root/FOMORADIO/config/persona_config.json
Traceback (most recent call last):
  File "/root/FOMORADIO/run.py", line 224, in <module>
    main()
  File "/root/FOMORADIO/run.py", line 113, in main
    contents, source = data_collectors()
                       ^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/run.py", line 73, in data_collectors
    return twitter_client.process(), twitter_client.source
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/data_collectors/collector.py", line 33, in process
    records, timestamp_key, content_key, user_key = self.fetch()
                                                    ^^^^^^^^^^^^
  File "/root/FOMORADIO/data_collectors/twitter_client.py", line 91, in fetch
    tweets = func()
             ^^^^^^
  File "/root/FOMORADIO/data_collectors/twitter_client.py", line 75, in get_latest_mentions
    return self.fetch_tweets(query)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/data_collectors/twitter_client.py", line 49, in fetch_tweets
    response = self.client.search_recent_tweets(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/env/lib/python3.12/site-packages/tweepy/client.py", line 1270, in search_recent_tweets
    return self._make_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/env/lib/python3.12/site-packages/tweepy/client.py", line 129, in _make_request
    response = self.request(method, route, params=request_params,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/env/lib/python3.12/site-packages/tweepy/client.py", line 115, in request
    raise TooManyRequests(response)
tweepy.errors.TooManyRequests: 429 Too Many Requests
Too Many Requests

After verifying API key (still good)

SECOND MESSAGE;

INFO:Fomo-FW:Video File saved as FomoRadioAI-1-e6abd50a-20241222_235611.mp4
Traceback (most recent call last):
  File "/root/FOMORADIO/run.py", line 224, in <module>
    main()
  File "/root/FOMORADIO/run.py", line 210, in main
    is_tweeted, posting_errors = twitter_consumer_client.post_tweet_with_media(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/consumers/twitter_client.py", line 70, in post_tweet_with_media
    is_uploaded, detail = self.upload_media(path)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/consumers/twitter_client.py", line 85, in upload_media
    media = self.api_client.media_upload(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/env/lib/python3.12/site-packages/tweepy/api.py", line 3483, in media_upload
    return self.chunked_upload(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/env/lib/python3.12/site-packages/tweepy/api.py", line 3594, in chunked_upload
    media_id = self.chunked_upload_init(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/env/lib/python3.12/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/FOMORADIO/env/lib/python3.12/site-packages/tweepy/api.py", line 3724, in chunked_upload_init
    return self.request(
           ^^^^^^^^^^^^^
  File "/root/FOMORADIO/env/lib/python3.12/site-packages/tweepy/api.py", line 269, in request
    raise Unauthorized(resp)
tweepy.errors.Unauthorized: 401 Unauthorized <--- THIS POPPED UP AFTER I VERIFIED API KEY;
89 - Invalid or expired token

NOTE: THE API KEY IS GOOD (I HAVE INTEGROMAT ENABLED ON X- SO i know the API key is good)

**Comment by g003223** [comment]
NOTE: I noticed that you do not have FLASK/ Rest API running to capture to authorize app in OAUTH 1.0 / 2

**Comment by g003223** [comment]
NOTE: Should have a backward compatible feature to support v1 vs v2 OAUTH

v# (Required) Twitter Authentication through OAUTH
[#v2](https://x.com/hashtag/v2?src=hashtag_click) auth w/ API (broken)
[#TWITTER_API_KEY](https://x.com/hashtag/TWITTER_API_KEY?src=hashtag_click)=
[#TWITTER_API_SECRET_KEY](https://x.com/hashtag/TWITTER_API_SECRET_KEY?src=hashtag_click)=
[#TWITTER_ACCESS_TOKEN](https://x.com/hashtag/TWITTER_ACCESS_TOKEN?src=hashtag_click)=
[#TWITTER_ACCESS_TOKEN_SECRET](https://x.com/hashtag/TWITTER_ACCESS_TOKEN_SECRET?src=hashtag_click)=

# v1 AUTH - Username/Password Support
TWITTER_USERNAME=fomoradio
TWITTER_PASSWORD="123456abacde"
TWITTER_EMAIL=ne@ne.me
TWITTER_POLL_INTERVAL=60

**Comment by g003223** [comment]
NOTE: Tweepy doesn't support v1 AUTH- Username/Password method

**Comment by g003223** [comment]
NOTE: Consider using ai16z twitter-client which does
https://github.com/elizaOS/agent-twitter-client.git
